
from pyfinviz.screener import Screener


country_by_display_name = {
    "USA": Screener.CountryOption.USA,
    "Foreign (ex-USA)": Screener.CountryOption.FOREIGN_EX_USA,
    "Asia": Screener.CountryOption.ASIA,
    "Europe": Screener.CountryOption.EUROPE,
    "Latin America": Screener.CountryOption.LATIN_AMERICA,
    "BRIC": Screener.CountryOption.BRIC,
    "Argentina": Screener.CountryOption.ARGENTINA,
    "Australia": Screener.CountryOption.AUSTRALIA,
    "Bahamas": Screener.CountryOption.BAHAMAS,
    "Belgium": Screener.CountryOption.BELGIUM,
    "Benelux": Screener.CountryOption.BENELUX,
    "Bermuda": Screener.CountryOption.BERMUDA,
    "Brazil": Screener.CountryOption.BRAZIL,
    "Canada": Screener.CountryOption.CANADA,
    "Cayman Islands": Screener.CountryOption.CAYMAN_ISLANDS,
    "Chile": Screener.CountryOption.CHILE,
    "China": Screener.CountryOption.CHINA,
    "China & Hong Kong": Screener.CountryOption.CHINA_AND_HONG_KONG,
    "Colombia": Screener.CountryOption.COLOMBIA,
    "Cyprus": Screener.CountryOption.CYPRUS,
    "Denmark": Screener.CountryOption.DENMARK,
    "Finland": Screener.CountryOption.FINLAND,
    "France": Screener.CountryOption.FRANCE,
    "Germany": Screener.CountryOption.GERMANY,
    "Greece": Screener.CountryOption.GREECE,
    "Hong Kong": Screener.CountryOption.HONG_KONG,
    "Hungary": Screener.CountryOption.HUNGARY,
    "Iceland": Screener.CountryOption.ICELAND,
    "India": Screener.CountryOption.INDIA,
    "Indonesia": Screener.CountryOption.INDONESIA,
    "Ireland": Screener.CountryOption.IRELAND,
    "Israel": Screener.CountryOption.ISRAEL,
    "Italy": Screener.CountryOption.ITALY,
    "Japan": Screener.CountryOption.JAPAN,
    "Kazakhstan": Screener.CountryOption.KAZAKHSTAN,
    "Luxembourg": Screener.CountryOption.LUXEMBOURG,
    "Malaysia": Screener.CountryOption.MALAYSIA,
    "Malta": Screener.CountryOption.MALTA,
    "Mexico": Screener.CountryOption.MEXICO,
    "Monaco": Screener.CountryOption.MONACO,
    "Netherlands": Screener.CountryOption.NETHERLANDS,
    "New Zealand": Screener.CountryOption.NEW_ZEALAND,
    "Norway": Screener.CountryOption.NORWAY,
    "Panama": Screener.CountryOption.PANAMA,
    "Peru": Screener.CountryOption.PERU,
    "Philippines": Screener.CountryOption.PHILIPPINES,
    "Portugal": Screener.CountryOption.PORTUGAL,
    "Russia": Screener.CountryOption.RUSSIA,
    "Singapore": Screener.CountryOption.SINGAPORE,
    "South Africa": Screener.CountryOption.SOUTH_AFRICA,
    "South Korea": Screener.CountryOption.SOUTH_KOREA,
    "Spain": Screener.CountryOption.SPAIN,
    "Sweden": Screener.CountryOption.SWEDEN,

    "Switzerland": Screener.CountryOption.SWITZERLAND,
    "Taiwan": Screener.CountryOption.TAIWAN,
    "Turkey": Screener.CountryOption.TURKEY,
    "United Arab Emirates": Screener.CountryOption.UNITED_ARAB_EMIRATES,
    "United Kingdom": Screener.CountryOption.UNITED_KINGDOM,
    "Uruguay": Screener.CountryOption.URUGUAY,
    "Custom": Screener.CountryOption.CUSTOM_ELITE_ONLY

}